name: learn-github-actions
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        env:
          PAGE_ID: ${{secrets.PAGE_ID}}
          ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}} 